2025-07-12 18:19:45,299 INFO    Thread-2 (_run_job):34294 [wandb_setup.py:_flush():81] Current SDK version is 0.20.0
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_setup.py:_flush():81] Configure stats pid to 34294
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_setup.py:_flush():81] Loading settings from /Users/nbhsbgnb/.config/wandb/settings
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_setup.py:_flush():81] Loading settings from /Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/wandb/settings
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/wandb/run-20250712_181945-2dlnyzfu/logs/debug.log
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/nbhsbgnb/PycharmProjects/PythonProject/PowerPINN/wandb/run-20250712_181945-2dlnyzfu/logs/debug-internal.log
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():831] calling init triggers
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():836] wandb.init called with sweep_config: {'seed': 1, 'weight_data': 1, 'weight_dt': 0.001, 'weight_pinn': 0.0001, 'weight_pinn_ic': 0.001}
config: {'_wandb': {}}
2025-07-12 18:19:45,300 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():872] starting backend
2025-07-12 18:19:45,525 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():875] sending inform_init request
2025-07-12 18:19:45,549 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():883] backend started and connected
2025-07-12 18:19:45,550 INFO    Thread-2 (_run_job):34294 [wandb_run.py:_config_callback():1358] config_cb None None {'seed': 1, 'weight_data': 1, 'weight_dt': 0.001, 'weight_pinn': 0.0001, 'weight_pinn_ic': 0.001}
2025-07-12 18:19:45,552 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():956] updated telemetry
2025-07-12 18:19:45,569 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-07-12 18:19:46,110 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():1032] starting run threads in backend
2025-07-12 18:19:46,151 INFO    Thread-2 (_run_job):34294 [wandb_run.py:_console_start():2453] atexit reg
2025-07-12 18:19:46,151 INFO    Thread-2 (_run_job):34294 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-07-12 18:19:46,151 INFO    Thread-2 (_run_job):34294 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-07-12 18:19:46,151 INFO    Thread-2 (_run_job):34294 [wandb_run.py:_redirect():2393] Redirects installed.
2025-07-12 18:19:46,152 INFO    Thread-2 (_run_job):34294 [wandb_init.py:init():1078] run started, returning control to user process
2025-07-12 18:20:39,609 WARNING MsgRouterThr:34294 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-12 18:20:39,611 INFO    MsgRouterThr:34294 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
